apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service
  namespace: ecommerce

spec:
  replicas: 1

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
        - name: product-service
          image: ankit97leo/product-service:jenkins-14

          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /products
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          env:
            - name: DB_HOST
              value: mysql

            - name: DB_USER
              value: root

            - name: DB_PASSWORD
              value: password

            - name: DB_NAME
              value: ecommerce