apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: ecommerce

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: ankit97leo/frontend:manual-1

          ports:
            - containerPort: 3000

          env:
            - name: DB_HOST
              value: mysql

            - name: DB_USER
              value: root

            - name: DB_PASSWORD
              value: password

            - name: DB_NAME
              value: ecommerce