pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Project') {
            steps {
                sh 'echo "Jenkins successfully checked out the capstone project"'
                sh 'ls -la'
            }
        }

        stage('Docker Check') {
            steps {
                sh 'docker --version'
                sh 'docker ps'
            }
        }

        stage('Build Product Service') {
            steps {
                sh '''
                    docker build \
                      -t ankit97leo/product-service:jenkins-${BUILD_NUMBER} \
                      -f docker/backend.Dockerfile \
                      ./product-service
                '''
            }
        }

        stage('Build Order Service') {
            steps {
                sh '''
                    docker build \
                      -t ankit97leo/order-service:jenkins-${BUILD_NUMBER} \
                      -f docker/backend.Dockerfile \
                      ./order-service
                '''
            }
        }

        stage('Build Inventory Service') {
            steps {
                sh '''
                    docker build \
                      -t ankit97leo/inventory-service:jenkins-${BUILD_NUMBER} \
                      -f docker/backend.Dockerfile \
                      ./inventory-service
                '''
            }
        }

        stage('Build Frontend') {
            steps {
                sh '''
                    docker build \
                      -t ankit97leo/frontend:jenkins-${BUILD_NUMBER} \
                      -f docker/frontend.Dockerfile \
                      ./frontend
                '''
            }
        }
    }

    post {
        success {
            echo 'All application Docker images built successfully.'
        }

        failure {
            echo 'CI pipeline failed.'
        }
    }
}