pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Project') {
            steps {
                sh 'echo "Jenkins successfully checked out the capstone project"'
                sh 'ls -la'
            }
        }

        stage('Docker Check') {
            steps {
                sh 'docker --version'
                sh 'docker ps'
            }
        }

        stage('Build Product Service') {
            steps {
                sh '''
                    docker build \
                      -t ankit97leo/product-service:jenkins-${BUILD_NUMBER} \
                      -f docker/backend.Dockerfile \
                      ./product-service
                '''
            }
        }
    }

    post {
        success {
            echo 'CI pipeline completed successfully.'
        }

        failure {
            echo 'CI pipeline failed.'
        }
    }
}